"""Deterministic ODF list labels, reconstructed the way LibreOffice draws them.

An ODT list paragraph can display a generated label (``1.``, ``(5)``, ``II.``)
that is not part of its character data.  This module reproduces those labels
from the document's list styles, list structure and continuation attributes,
following the LibreOffice Writer import and numbering rules:

* list identity: a root ``text:list`` opens a new list unless
  ``text:continue-list`` names a processed list or ``text:continue-numbering``
  continues the immediately preceding list of the same style; in documents
  generated by Microsoft Office it continues the last list of that style;
* counting: the paragraphs of one list form a number tree.  The first
  paragraph of a ``text:list-item`` is counted; later paragraphs, paragraphs
  after a nested list and ``text:list-header`` paragraphs are not.  A missing
  parent level becomes a phantom that counts when it has counted children,
  and the first child of an uncounted parent continues the previous subtree.
  ``text:start-value`` on an item, and a second sub-list in one item, restart;
* labels: prefix, the level number in its number format and suffix, or the
  ``num-list-format`` string; ``text:display-levels`` joins parent numbers.

For a document generated by Microsoft Office the label must also be the one
that office suite prints: the plain per-level counter model must give the
same numbers, the ODF 1.4 ``number:num-list-format`` string must equal the
prefix/suffix form, and a number format must render identically in both
suites for the value at hand.  A paragraph is labelled only when every rule
it depends on is implemented here; bullets, images, unknown number formats,
style overrides, consecutive numbering, paragraph-style numbering outside a
list, lists inside frames or notes and any other unimplemented feature make
the paragraph ``unsupported`` so the caller can fail closed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping
from xml.etree import ElementTree


LIST_LABEL_RULE_VERSION = "nhi-rule-history/odf-list-label/1.0.0"

_OFFICE = "urn:oasis:names:tc:opendocument:xmlns:office:1.0"
_TEXT = "urn:oasis:names:tc:opendocument:xmlns:text:1.0"
_STYLE = "urn:oasis:names:tc:opendocument:xmlns:style:1.0"
_NUMBER = "urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"
_DRAW = "urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
_META = "urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
_LOEXT = "urn:org:documentfoundation:names:experimental:office:xmlns:loext:1.0"
_XML = "http://www.w3.org/XML/1998/namespace"

_TAG_P = f"{{{_TEXT}}}p"
_TAG_H = f"{{{_TEXT}}}h"
_TAG_LIST = f"{{{_TEXT}}}list"
_TAG_LIST_ITEM = f"{{{_TEXT}}}list-item"
_TAG_LIST_HEADER = f"{{{_TEXT}}}list-header"
_TAG_NUMBERED_PARAGRAPH = f"{{{_TEXT}}}numbered-paragraph"
_TAG_SOFT_PAGE_BREAK = f"{{{_TEXT}}}soft-page-break"
_TAG_NOTE = f"{{{_TEXT}}}note"
_TAG_ANNOTATION = f"{{{_OFFICE}}}annotation"
_TAG_FRAME = f"{{{_DRAW}}}frame"
_TAG_LIST_STYLE = f"{{{_TEXT}}}list-style"
_TAG_OUTLINE_STYLE = f"{{{_TEXT}}}outline-style"
_TAG_OUTLINE_LEVEL = f"{{{_TEXT}}}outline-level-style"
_TAG_LEVEL_NUMBER = f"{{{_TEXT}}}list-level-style-number"
_TAG_LEVEL_BULLET = f"{{{_TEXT}}}list-level-style-bullet"
_TAG_LEVEL_IMAGE = f"{{{_TEXT}}}list-level-style-image"
_TAG_LEVEL_PROPERTIES = f"{{{_STYLE}}}list-level-properties"
_TAG_LABEL_ALIGNMENT = f"{{{_STYLE}}}list-level-label-alignment"
_TAG_STYLE = f"{{{_STYLE}}}style"
_TAG_AUTOMATIC_STYLES = f"{{{_OFFICE}}}automatic-styles"
_TAG_COMMON_STYLES = f"{{{_OFFICE}}}styles"
_TAG_WORD_LIST_FORMAT = f"{{{_NUMBER}}}num-list-format"
_TAG_WORD_LIST_LABEL = f"{{{_NUMBER}}}num-list-label"
_TAG_WORD_TEXT = f"{{{_NUMBER}}}text"
_TAG_GENERATOR = f"{{{_META}}}generator"

_ATTR_STYLE_NAME = f"{{{_STYLE}}}name"
_ATTR_FAMILY = f"{{{_STYLE}}}family"
_ATTR_PARENT = f"{{{_STYLE}}}parent-style-name"
_ATTR_PARA_LIST_STYLE = f"{{{_STYLE}}}list-style-name"
_ATTR_DEFAULT_OUTLINE = f"{{{_STYLE}}}default-outline-level"
_ATTR_TEXT_STYLE = f"{{{_TEXT}}}style-name"
_ATTR_LEVEL = f"{{{_TEXT}}}level"
_ATTR_OUTLINE_LEVEL = f"{{{_TEXT}}}outline-level"
_ATTR_IS_LIST_HEADER = f"{{{_TEXT}}}is-list-header"
_ATTR_CONTINUE_NUMBERING = f"{{{_TEXT}}}continue-numbering"
_ATTR_CONTINUE_LIST = f"{{{_TEXT}}}continue-list"
_ATTR_XML_ID = f"{{{_XML}}}id"
_ATTR_LIST_ID = f"{{{_TEXT}}}list-id"
_ATTR_START = f"{{{_TEXT}}}start-value"
_ATTR_STYLE_OVERRIDE = f"{{{_TEXT}}}style-override"
_ATTR_DISPLAY_LEVELS = f"{{{_TEXT}}}display-levels"
_ATTR_CONSECUTIVE = f"{{{_TEXT}}}consecutive-numbering"
_ATTR_NUM_FORMAT = f"{{{_STYLE}}}num-format"
_ATTR_NUM_PREFIX = f"{{{_STYLE}}}num-prefix"
_ATTR_NUM_SUFFIX = f"{{{_STYLE}}}num-suffix"
_ATTR_LETTER_SYNC = f"{{{_STYLE}}}num-letter-sync"
_ATTR_LIST_FORMAT = f"{{{_STYLE}}}num-list-format"
_ATTR_LO_LIST_FORMAT = f"{{{_LOEXT}}}num-list-format"
_ATTR_LO_IS_LEGAL = f"{{{_LOEXT}}}is-legal"
_ATTR_WORD_FORMAT_NAME = f"{{{_STYLE}}}num-list-format-name"
_ATTR_POSITION_MODE = f"{{{_TEXT}}}list-level-position-and-space-mode"
_ATTR_FOLLOWED_BY = f"{{{_TEXT}}}label-followed-by"

MSO_GENERATOR_PREFIX = "MicrosoftOffice"
# Writer number rules have ten levels; a deeper list is clamped to the last.
MAX_LEVELS = 10
# LibreOffice's plain-text export indents each numbering level by four spaces.
EXPORT_INDENT = "    "
# The printed gap after a label, by ``text:label-followed-by``.
_FOLLOWED_BY = {"listtab": "\t", "space": " ", "nothing": ""}
_SHRT_MAX = 32767

_ROMAN = (
    (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"), (100, "C"), (90, "XC"),
    (50, "L"), (40, "XL"), (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
)
_TIAN_GAN = "甲乙丙丁戊己庚辛壬癸"
_DI_ZI = "子丑寅卯辰巳午未申酉戌亥"
_UPPER_ZH_TW = "壹貳參肆伍陸柒捌玖"
_LOWER_ZH = "一二三四五六七八九"


class ListNumberingUnsupported(Exception):
    """A list feature this module does not reproduce; carries a reason code."""

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


@dataclass(frozen=True)
class ListLabel:
    """How one paragraph is numbered.

    ``status`` is ``labelled`` (a label is drawn), ``unlabelled`` (the
    paragraph belongs to a list but draws no label) or ``unsupported``.
    ``export_prefix`` is what LibreOffice's plain-text export writes before
    the paragraph text: indentation, the label or a placeholder, and a space.
    """

    status: str
    label: str = ""
    separator: str = ""
    export_prefix: str = ""
    reason: str | None = None
    evidence: Mapping[str, Any] = field(default_factory=dict)

    @property
    def printed_prefix(self) -> str:
        """The generated text printed before the paragraph's own text."""

        if self.status != "labelled":
            return ""
        return self.label + self.separator


# ---------------------------------------------------------------------------
# Styles


@dataclass(frozen=True)
class _Level:
    kind: str
    level: int
    num_format: str
    letter_sync: bool
    prefix: str
    suffix: str
    list_format: str | None
    word_format_name: str | None
    start: int
    display_levels: int
    position_mode: str | None
    followed_by: str
    is_legal: bool
    malformed: str | None


@dataclass(frozen=True)
class _ListStyle:
    name: str
    origin: str
    consecutive: bool
    levels: Mapping[int, _Level]
    signature: str


def _int_attribute(value: str | None) -> int | None:
    if value is None:
        return None
    text = value.strip()
    if not text or not (text.isdigit() or (text[0] == "-" and text[1:].isdigit())):
        raise ValueError(value)
    return int(text)


def _parse_level(node: ElementTree.Element) -> _Level:
    kind = {
        _TAG_LEVEL_NUMBER: "number",
        _TAG_LEVEL_BULLET: "bullet",
        _TAG_LEVEL_IMAGE: "image",
        _TAG_OUTLINE_LEVEL: "number",
    }[node.tag]
    malformed = None
    try:
        level = _int_attribute(node.attrib.get(_ATTR_LEVEL))
        start = _int_attribute(node.attrib.get(_ATTR_START))
        display = _int_attribute(node.attrib.get(_ATTR_DISPLAY_LEVELS))
    except ValueError:
        level, start, display, malformed = None, None, None, "list_level_attribute"
    # LibreOffice clamps these exactly this way on import.
    level = max(level or 0, 1)
    start = 1 if start is None or start < 0 else min(start, _SHRT_MAX)
    display = 1 if display is None or display < 1 else min(display, _SHRT_MAX)
    position_mode = None
    # LibreOffice's default when no label alignment names one.
    followed_by = "listtab"
    for child in node:
        if child.tag != _TAG_LEVEL_PROPERTIES:
            continue
        position_mode = child.attrib.get(_ATTR_POSITION_MODE)
        for grandchild in child:
            if grandchild.tag == _TAG_LABEL_ALIGNMENT:
                followed_by = grandchild.attrib.get(_ATTR_FOLLOWED_BY, "listtab")
    list_format = node.attrib.get(_ATTR_LIST_FORMAT)
    if list_format is None:
        list_format = node.attrib.get(_ATTR_LO_LIST_FORMAT)
    return _Level(
        kind=kind,
        level=level,
        # A number level without style:num-format is Arabic in LibreOffice.
        num_format=node.attrib.get(_ATTR_NUM_FORMAT, "1") if kind == "number" else "",
        letter_sync=node.attrib.get(_ATTR_LETTER_SYNC) == "true",
        prefix=node.attrib.get(_ATTR_NUM_PREFIX, ""),
        suffix=node.attrib.get(_ATTR_NUM_SUFFIX, ""),
        list_format=list_format,
        word_format_name=node.attrib.get(_ATTR_WORD_FORMAT_NAME),
        start=start if kind == "number" else 1,
        display_levels=display if kind == "number" else 1,
        position_mode=position_mode,
        followed_by=followed_by,
        is_legal=node.attrib.get(_ATTR_LO_IS_LEGAL) == "true",
        malformed=malformed,
    )


def _signature(node: ElementTree.Element) -> str:
    def canonical(element: ElementTree.Element) -> str:
        attributes = "".join(
            f" {key}={value!r}" for key, value in sorted(element.attrib.items())
            if key != _ATTR_STYLE_NAME
        )
        children = "".join(canonical(child) for child in element)
        return f"<{element.tag}{attributes}>{children}</>"

    return canonical(node)


def _parse_list_style(node: ElementTree.Element, origin: str) -> _ListStyle:
    levels: dict[int, _Level] = {}
    for child in node:
        if child.tag in {_TAG_LEVEL_NUMBER, _TAG_LEVEL_BULLET, _TAG_LEVEL_IMAGE}:
            parsed = _parse_level(child)
            levels.setdefault(parsed.level, parsed)
    return _ListStyle(
        name=node.attrib.get(_ATTR_STYLE_NAME, ""),
        origin=origin,
        consecutive=node.attrib.get(_ATTR_CONSECUTIVE) == "true",
        levels=levels,
        signature=_signature(node),
    )


def _word_list_formats(
    *roots: ElementTree.Element | None,
) -> dict[str, dict[int, str] | None]:
    """ODF 1.4 ``number:num-list-format`` strings by name and level.

    Microsoft Word writes each level as a ``number:num-list-label`` marker
    followed by one ``number:text``.  Any other shape maps to ``None``.
    """

    found: dict[str, dict[int, str] | None] = {}
    for root in roots:
        if root is None:
            continue
        for node in root.iter(_TAG_WORD_LIST_FORMAT):
            name = node.attrib.get(_ATTR_STYLE_NAME, "")
            children = list(node)
            parsed: dict[int, str] | None = {}
            if len(children) % 2:
                parsed = None
            else:
                for marker, text in zip(children[::2], children[1::2]):
                    try:
                        level = _int_attribute(marker.attrib.get(_ATTR_LEVEL))
                    except ValueError:
                        level = None
                    if (
                        marker.tag != _TAG_WORD_LIST_LABEL
                        or text.tag != _TAG_WORD_TEXT
                        or level is None
                        or level in parsed
                        or len(text)
                    ):
                        parsed = None
                        break
                    parsed[level] = text.text or ""
            if name in found and found[name] != parsed:
                parsed = None
            found[name] = parsed
    return found


class _Styles:
    """List and paragraph styles of one document, resolved like LibreOffice."""

    def __init__(
        self,
        content: ElementTree.Element,
        styles: ElementTree.Element | None,
    ) -> None:
        self.common_lists: dict[str, _ListStyle] = {}
        self.automatic_lists: dict[str, _ListStyle] = {}
        self.automatic_paragraphs: dict[str, ElementTree.Element] = {}
        self.common_paragraphs: dict[str, ElementTree.Element] = {}
        self.outline: ElementTree.Element | None = None
        automatic = content.find(_TAG_AUTOMATIC_STYLES)
        if automatic is not None:
            for node in automatic:
                if node.tag == _TAG_LIST_STYLE:
                    style = _parse_list_style(node, "automatic")
                    self.automatic_lists.setdefault(style.name, style)
                elif node.tag == _TAG_STYLE and node.attrib.get(
                    _ATTR_FAMILY
                ) == "paragraph":
                    self.automatic_paragraphs.setdefault(
                        node.attrib.get(_ATTR_STYLE_NAME, ""), node
                    )
        common = styles.find(_TAG_COMMON_STYLES) if styles is not None else None
        if common is not None:
            for node in common:
                if node.tag == _TAG_LIST_STYLE:
                    style = _parse_list_style(node, "common")
                    self.common_lists.setdefault(style.name, style)
                elif node.tag == _TAG_STYLE and node.attrib.get(
                    _ATTR_FAMILY
                ) == "paragraph":
                    self.common_paragraphs.setdefault(
                        node.attrib.get(_ATTR_STYLE_NAME, ""), node
                    )
                elif node.tag == _TAG_OUTLINE_STYLE and self.outline is None:
                    self.outline = node
        self.word_formats = _word_list_formats(content, styles)

    def list_style(self, name: str) -> _ListStyle:
        """LibreOffice looks up numbering styles before automatic styles."""

        common = self.common_lists.get(name)
        automatic = self.automatic_lists.get(name)
        if common is not None and automatic is not None:
            if common.signature != automatic.signature:
                raise ListNumberingUnsupported("list_style_name_ambiguous")
            return common
        if common is not None:
            return common
        if automatic is not None:
            return automatic
        raise ListNumberingUnsupported("list_style_unresolved")

    def paragraph_list_style(self, name: str | None) -> str | None:
        """The list style named by a paragraph's style chain, if any."""

        style = self.automatic_paragraphs.get(name or "")
        if style is None:
            style = self.common_paragraphs.get(name or "")
        seen: set[int] = set()
        while style is not None and id(style) not in seen:
            seen.add(id(style))
            if _ATTR_PARA_LIST_STYLE in style.attrib:
                return style.attrib[_ATTR_PARA_LIST_STYLE]
            style = self.common_paragraphs.get(
                style.attrib.get(_ATTR_PARENT) or ""
            )
        return None

    def outline_level_draws(self, level: str | None) -> bool:
        """Whether the outline style draws anything at an outline level.

        A level without ``style:num-format`` is Arabic in LibreOffice.
        """

        if self.outline is None or not level:
            return False
        for child in self.outline:
            if child.tag == _TAG_OUTLINE_LEVEL and child.attrib.get(
                _ATTR_LEVEL
            ) == level:
                return bool(
                    child.attrib.get(_ATTR_NUM_FORMAT, "1")
                    or child.attrib.get(_ATTR_NUM_PREFIX)
                    or child.attrib.get(_ATTR_NUM_SUFFIX)
                )
        return False

    def paragraph_outline_level(self, name: str | None) -> str | None:
        """The default outline level named by a paragraph's style chain."""

        style = self.automatic_paragraphs.get(name or "")
        if style is None:
            style = self.common_paragraphs.get(name or "")
        seen: set[int] = set()
        while style is not None and id(style) not in seen:
            seen.add(id(style))
            if style.attrib.get(_ATTR_DEFAULT_OUTLINE):
                return style.attrib[_ATTR_DEFAULT_OUTLINE]
            style = self.common_paragraphs.get(
                style.attrib.get(_ATTR_PARENT) or ""
            )
        return None


# ---------------------------------------------------------------------------
# Number formats


def _roman(value: int) -> str:
    parts: list[str] = []
    for amount, symbol in _ROMAN:
        while value >= amount:
            parts.append(symbol)
            value -= amount
    return "".join(parts)


def _letters(value: int, alphabet: str, synchronized: bool) -> str:
    if synchronized:
        return alphabet[(value - 1) % 26] * ((value - 1) // 26 + 1)
    digits: list[str] = []
    index = value - 1
    while True:
        digits.append(alphabet[index % 26])
        if index < 26:
            break
        index = (index - 26) // 26
    return "".join(reversed(digits))


def format_number(
    value: int, num_format: str, *, letter_sync: bool, word_compatible: bool
) -> str:
    """Render one level number the way LibreOffice does.

    ``word_compatible`` restricts every format to values that Microsoft Word
    renders identically; anything else raises ``ListNumberingUnsupported``.
    """

    if num_format == "1":
        if value < 0:
            raise ListNumberingUnsupported("number_negative")
        return str(value)
    if value < 1:
        raise ListNumberingUnsupported("number_below_one")
    if num_format in {"a", "A"}:
        alphabet = (
            "abcdefghijklmnopqrstuvwxyz"
            if num_format == "a"
            else "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        )
        if word_compatible and not letter_sync and value > 26:
            # Word repeats letters (aa, bb); unsynchronized LibreOffice
            # letters continue aa, ab.
            raise ListNumberingUnsupported("number_format_range")
        return _letters(value, alphabet, letter_sync)
    if num_format in {"i", "I"}:
        if value > 3999:
            raise ListNumberingUnsupported("number_format_range")
        text = _roman(value)
        return text.lower() if num_format == "i" else text
    tables = {
        "甲, 乙, 丙, ...": _TIAN_GAN,
        "子, 丑, 寅, ...": _DI_ZI,
        "壹, 貳, 參, ...": _UPPER_ZH_TW,
        "一, 二, 三, ...": _LOWER_ZH,
    }
    table = tables.get(num_format)
    if table is not None:
        # Only the single-character values are reproduced; LibreOffice
        # switches to Arabic or composes numerals beyond them.
        if value > len(table):
            raise ListNumberingUnsupported("number_format_range")
        return table[value - 1]
    raise ListNumberingUnsupported("number_format_unsupported")


def _effective_list_format(level: _Level) -> str:
    """LibreOffice's list format string for one level."""

    if level.list_format is not None:
        return level.list_format
    shown = min(level.display_levels, level.level)
    placeholders = ".".join(
        f"%{level.level - shown + index + 1}%" for index in range(shown)
    )
    return level.prefix + placeholders + level.suffix


def _expand_list_format(
    template: str,
    level: int,
    numbers: Mapping[int, int],
    formats: Mapping[int, _Level],
    *,
    word_compatible: bool,
) -> tuple[str, tuple[int, ...]]:
    """Substitute ``%N%`` placeholders exactly as SwNumRule::MakeNumString."""

    out: list[str] = []
    used: list[int] = []
    position = 0
    while position < len(template):
        if template[position] != "%" or position + 2 >= len(template):
            out.append(template[position])
            position += 1
            continue
        if template.startswith("%10%", position):
            target, end = 10, position + 4
        elif (
            "1" <= template[position + 1] <= "9"
            and template[position + 2] == "%"
        ):
            target, end = int(template[position + 1]), position + 3
        else:
            out.append(template[position])
            position += 1
            continue
        if target > level:
            # There is no number for a deeper level: LibreOffice drops it.
            position = end
            continue
        target_format = formats.get(target)
        if target_format is None or target_format.kind != "number":
            raise ListNumberingUnsupported("list_format_level_undefined")
        if target_format.num_format == "":
            raise ListNumberingUnsupported("list_format_level_without_number")
        value = numbers.get(target)
        if value is None:
            raise ListNumberingUnsupported("list_format_level_without_number")
        out.append(
            "0"
            if value == 0
            else format_number(
                value,
                target_format.num_format,
                letter_sync=target_format.letter_sync,
                word_compatible=word_compatible,
            )
        )
        used.append(target)
        position = end
    return "".join(out), tuple(used)


# ---------------------------------------------------------------------------
# Traversal


@dataclass
class _Item:
    start_value: int | None


@dataclass
class _Block:
    parent: "_Block | None"
    style_name: str
    style: _ListStyle | None
    level: int
    list_id: str
    continue_id: str
    restart: bool
    item: _Item | None = None
    problem: str | None = None


@dataclass
class _Paragraph:
    element: ElementTree.Element
    order: int
    list_id: str
    level: int
    counted: bool
    restart: bool
    restart_value: int | None
    style: _ListStyle | None
    problem: str | None
    taints_list: bool
    source: str


def _embedded_containers(
    element: ElementTree.Element,
) -> Iterable[ElementTree.Element]:
    for child in element:
        if child.tag in {_TAG_NOTE, _TAG_ANNOTATION, _TAG_FRAME}:
            yield child
        elif child.tag not in {_TAG_P, _TAG_H}:
            yield from _embedded_containers(child)


class _Walker:
    """Replays LibreOffice's list-context stack over the document body."""

    def __init__(self, styles: _Styles, *, mso: bool) -> None:
        self.styles = styles
        self.mso = mso
        self.processed: dict[str, tuple[str, str]] = {}
        self.last_list_id = ""
        self.last_list_style: str | None = None
        self.style_last_list: dict[str, str] = {}
        self.generated = 0
        self.paragraphs: list[_Paragraph] = []
        self.outside: dict[int, ListLabel] = {}

    def _new_list_id(self) -> str:
        self.generated += 1
        return f"generated-list-{self.generated}"

    # LibreOffice keeps the list item on the list-context stack entry of the
    # innermost list block; a paragraph consumes it, a nested list's end and
    # an item's end clear it.
    def walk(
        self,
        node: ElementTree.Element,
        block: _Block | None,
        foreign: bool,
    ) -> None:
        for child in node:
            tag = child.tag
            if tag == _TAG_LIST:
                self._list(child, block, sub_list_index=0, foreign=foreign)
            elif tag in {_TAG_P, _TAG_H}:
                self._paragraph(child, block, foreign)
            elif tag == _TAG_NUMBERED_PARAGRAPH:
                self._numbered_paragraph(child, foreign)
            elif tag in {_TAG_NOTE, _TAG_ANNOTATION, _TAG_FRAME}:
                self.walk(child, None, True)
            else:
                self.walk(child, block, foreign)

    def _paragraph(
        self,
        element: ElementTree.Element,
        block: _Block | None,
        foreign: bool,
    ) -> None:
        if block is None:
            self._outside_list(element)
        else:
            self._list_paragraph(element, block)
        # Frames and notes anchored in a paragraph hold separate text.
        for container in _embedded_containers(element):
            self.walk(container, None, True)

    def _outside_list(self, element: ElementTree.Element) -> None:
        # Outline (chapter) numbering is not reproduced.  LibreOffice numbers
        # an outline-level heading even when its paragraph style is not
        # assigned to the outline, so any outline level that draws a label
        # is unsupported, as is a style chain assigned to such a level.
        if element.tag == _TAG_H and element.attrib.get(_ATTR_OUTLINE_LEVEL):
            if element.attrib.get(_ATTR_IS_LIST_HEADER) != "true" and (
                self.styles.outline_level_draws(
                    element.attrib.get(_ATTR_OUTLINE_LEVEL)
                )
            ):
                self.outside[id(element)] = ListLabel(
                    status="unsupported", reason="outline_number"
                )
            return
        if self.styles.outline_level_draws(
            self.styles.paragraph_outline_level(
                element.attrib.get(_ATTR_TEXT_STYLE)
            )
        ):
            self.outside[id(element)] = ListLabel(
                status="unsupported", reason="outline_number"
            )
            return
        named = self.styles.paragraph_list_style(
            element.attrib.get(_ATTR_TEXT_STYLE)
        )
        if named:
            # LibreOffice drops paragraph-style numbering outside a list;
            # the producing suite may not.
            self.outside[id(element)] = ListLabel(
                status="unsupported",
                reason="paragraph_style_numbering_outside_list",
            )

    def _list_paragraph(
        self, element: ElementTree.Element, block: _Block
    ) -> None:
        item = block.item
        counted = item is not None
        restart = False
        if block.restart:
            restart = True
            block.restart = False
        restart_value = item.start_value if item is not None else None
        if restart_value is not None:
            restart = True
        # Inside a list LibreOffice numbers with the list's style whatever
        # list style the paragraph style names.
        problem = block.problem
        taints = problem is not None
        if problem is None and element.tag == _TAG_H:
            problem = "heading_in_list"
        self.paragraphs.append(
            _Paragraph(
                element=element,
                order=len(self.paragraphs),
                list_id=block.continue_id or block.list_id,
                level=min(block.level, MAX_LEVELS - 1),
                counted=counted,
                restart=restart,
                restart_value=restart_value,
                style=block.style,
                problem=problem,
                taints_list=taints,
                source="list",
            )
        )
        block.item = None

    def _list(
        self,
        element: ElementTree.Element,
        parent: _Block | None,
        *,
        sub_list_index: int,
        foreign: bool,
    ) -> None:
        attributes = element.attrib
        continue_attribute = attributes.get(_ATTR_CONTINUE_NUMBERING)
        style_name = attributes.get(_ATTR_TEXT_STYLE)
        problem: str | None = None
        if foreign:
            problem = "list_in_frame_or_note"
        if parent is not None:
            restart = parent.restart or sub_list_index > 1
            if continue_attribute is not None:
                restart = continue_attribute != "true"
            name = parent.style_name if style_name is None else style_name
            if name != parent.style_name:
                problem = problem or "nested_list_style_differs"
            block = _Block(
                parent=parent,
                style_name=name,
                style=parent.style,
                level=parent.level + 1,
                list_id=parent.list_id,
                continue_id=parent.continue_id,
                restart=restart,
                problem=problem or parent.problem,
            )
            if block.level >= MAX_LEVELS:
                block.problem = block.problem or "list_level_too_deep"
        else:
            restart = (
                continue_attribute is not None and continue_attribute != "true"
            )
            style: _ListStyle | None = None
            if not style_name:
                # LibreOffice would invent a default rule.
                problem = problem or "list_style_missing"
            else:
                try:
                    style = self.styles.list_style(style_name)
                except ListNumberingUnsupported as exc:
                    problem = problem or exc.reason
            if style is not None and style.consecutive:
                problem = problem or "consecutive_numbering"
            list_id = attributes.get(_ATTR_XML_ID) or self._new_list_id()
            if self.processed.get(list_id, ("", ""))[0].startswith("numbered:"):
                problem = problem or "numbered_paragraph_list_shared"
            continue_id = attributes.get(_ATTR_CONTINUE_LIST, "")
            if continue_attribute is not None and not restart and not continue_id:
                if (
                    self.last_list_style == (style_name or "")
                    and self.last_list_id != list_id
                ):
                    continue_id = self.last_list_id
            if (
                not continue_id
                and continue_attribute is not None
                and not restart
                and self.mso
            ):
                continue_id = self.style_last_list.get(style_name or "", "")
            if continue_id:
                if continue_id not in self.processed:
                    continue_id = ""
                else:
                    master = self.processed[continue_id][1]
                    while master:
                        continue_id = master
                        master = self.processed[continue_id][1]
            if list_id not in self.processed:
                self.processed[list_id] = (style_name or "", continue_id)
                self.last_list_id = list_id
                self.last_list_style = style_name or ""
                self.style_last_list[style_name or ""] = list_id
            block = _Block(
                parent=None,
                style_name=style_name or "",
                style=style,
                level=0,
                list_id=list_id,
                continue_id=continue_id,
                restart=restart,
                problem=problem,
            )
        for child in element:
            if child.tag in {_TAG_LIST_ITEM, _TAG_LIST_HEADER}:
                self._item(child, block, foreign)
            elif child.tag != _TAG_SOFT_PAGE_BREAK:
                block.problem = block.problem or "unexpected_list_child"
                self._taint_later(block)
        if parent is not None:
            parent.restart = block.restart
            parent.item = None

    def _item(
        self, element: ElementTree.Element, block: _Block, foreign: bool
    ) -> None:
        header = element.tag == _TAG_LIST_HEADER
        start_value: int | None = None
        if not header and _ATTR_START in element.attrib:
            try:
                value = _int_attribute(element.attrib[_ATTR_START])
            except ValueError:
                value = None
                block.problem = block.problem or "list_item_attribute"
            if value is not None and 0 <= value <= _SHRT_MAX:
                start_value = value
        if _ATTR_STYLE_OVERRIDE in element.attrib:
            block.problem = block.problem or "list_item_style_override"
        if not header:
            block.item = _Item(start_value=start_value)
        sub_lists = 0
        for child in element:
            if child.tag in {_TAG_P, _TAG_H}:
                self._paragraph(child, block, foreign)
            elif child.tag == _TAG_LIST:
                sub_lists += 1
                self._list(child, block, sub_list_index=sub_lists, foreign=foreign)
            elif child.tag != _TAG_SOFT_PAGE_BREAK:
                block.problem = block.problem or "unexpected_list_item_child"
                self._taint_later(block)
        block.item = None

    def _taint_later(self, block: _Block) -> None:
        self.paragraphs.append(
            _Paragraph(
                element=ElementTree.Element("taint"),
                order=len(self.paragraphs),
                list_id=block.continue_id or block.list_id,
                level=0,
                counted=False,
                restart=False,
                restart_value=None,
                style=block.style,
                problem=block.problem,
                taints_list=True,
                source="taint",
            )
        )

    def _numbered_paragraph(
        self, element: ElementTree.Element, foreign: bool
    ) -> None:
        """``text:numbered-paragraph`` with an explicit list id and style."""

        problem: str | None = "list_in_frame_or_note" if foreign else None
        list_id = element.attrib.get(_ATTR_LIST_ID, "")
        style_name = element.attrib.get(_ATTR_TEXT_STYLE, "")
        style: _ListStyle | None = None
        level = 0
        start_value: int | None = None
        try:
            parsed_level = _int_attribute(element.attrib.get(_ATTR_LEVEL))
            parsed_start = _int_attribute(element.attrib.get(_ATTR_START))
        except ValueError:
            parsed_level, parsed_start = None, None
            problem = problem or "numbered_paragraph_attribute"
        if parsed_level is not None and parsed_level >= 1:
            level = parsed_level - 1
        if parsed_start is not None and 0 <= parsed_start <= _SHRT_MAX:
            start_value = parsed_start
        if not list_id or not style_name:
            # Without both, LibreOffice derives the list from per-level state.
            problem = problem or "numbered_paragraph_without_list_id_or_style"
        else:
            try:
                style = self.styles.list_style(style_name)
            except ListNumberingUnsupported as exc:
                problem = problem or exc.reason
            known = self.processed.get(list_id)
            if known is not None and known[0] != f"numbered:{style_name}":
                problem = problem or "numbered_paragraph_list_shared"
            self.processed.setdefault(list_id, (f"numbered:{style_name}", ""))
        if level >= MAX_LEVELS:
            problem = problem or "list_level_too_deep"
        paragraphs = [
            child for child in element if child.tag in {_TAG_P, _TAG_H}
        ]
        if len(paragraphs) != 1 or len(paragraphs) != len(
            [child for child in element if child.tag != _TAG_SOFT_PAGE_BREAK]
        ):
            problem = problem or "numbered_paragraph_content"
        for child in paragraphs:
            self.paragraphs.append(
                _Paragraph(
                    element=child,
                    order=len(self.paragraphs),
                    list_id=f"numbered:{list_id}",
                    level=level,
                    counted=True,
                    restart=start_value is not None,
                    restart_value=start_value,
                    style=style,
                    problem=problem
                    or ("heading_in_list" if child.tag == _TAG_H else None),
                    taints_list=problem is not None,
                    source="numbered-paragraph",
                )
            )


# ---------------------------------------------------------------------------
# Numbering


class _Node:
    __slots__ = ("paragraph", "parent", "children", "number", "depth")

    def __init__(
        self, paragraph: _Paragraph | None, parent: "_Node | None"
    ) -> None:
        self.paragraph = paragraph
        self.parent = parent
        self.children: list[_Node] = []
        self.number = 0
        self.depth = -1 if parent is None else parent.depth + 1

    @property
    def phantom(self) -> bool:
        return self.paragraph is None and self.parent is not None


class _Tree:
    """One list's SwNumberTree: insertion with phantoms and validation."""

    def __init__(self, style: _ListStyle) -> None:
        self.style = style
        self.root = _Node(None, None)

    def add(self, paragraph: _Paragraph) -> _Node:
        parent = self.root
        for _ in range(paragraph.level):
            if not parent.children:
                parent.children.append(_Node(None, parent))
            parent = parent.children[-1]
        node = _Node(paragraph, parent)
        parent.children.append(node)
        return node

    def counted(self, node: _Node) -> bool:
        if node.paragraph is not None:
            return node.paragraph.counted
        if node.parent is None:
            return True
        # Phantoms count when they have counted children (count-phantoms).
        return self.has_counted_children(node)

    def counted_for_numbering(self, node: _Node) -> bool:
        if node.paragraph is None:
            return self.counted(node)
        level = self.style.levels.get(node.depth + 1)
        return node.paragraph.counted and level is not None and (
            level.kind != "number" or level.num_format != ""
        )

    def has_counted_children(self, node: _Node) -> bool:
        return any(
            self.counted_for_numbering(child) or self.has_counted_children(child)
            for child in node.children
        )

    def has_phantom_counted_parent(self, node: _Node) -> bool:
        parent = node.parent
        if parent is None:
            return False
        if parent.parent is None:
            return True
        if not parent.phantom:
            return self.counted(parent)
        return self.counted(parent) and self.has_phantom_counted_parent(parent)

    def start_value(self, node: _Node) -> int:
        paragraph = node.paragraph
        if (
            paragraph is not None
            and paragraph.restart
            and paragraph.restart_value is not None
        ):
            return paragraph.restart_value
        level = self.style.levels.get(node.depth + 1)
        return level.start if level is not None else 1

    def validate(self, parent: _Node) -> None:
        """SwNumberTreeNode::ValidateHierarchical, then the children."""

        children = parent.children
        if children:
            first = children[0]
            number = self.start_value(first)
            if not self.counted(first) and (
                not self.has_counted_children(first) or first.phantom
            ):
                number -= 1
            parent_counted = self.counted(parent) and (
                not parent.phantom or self.has_phantom_counted_parent(parent)
            )
            first_restarts = (
                first.paragraph is not None and first.paragraph.restart
            )
            if (
                not first_restarts
                and parent.parent is not None
                and not parent_counted
            ):
                siblings = parent.parent.children
                for previous in reversed(siblings[: siblings.index(parent)]):
                    if previous.children:
                        number = previous.children[-1].number
                        if self.counted(first) and (
                            not first.phantom
                            or self.has_phantom_counted_parent(first)
                        ):
                            number += 1
                        break
                    if self.counted(previous):
                        break
            first.number = number
            for child in children[1:]:
                if self.counted(child):
                    restarts = (
                        child.paragraph is not None and child.paragraph.restart
                    )
                    number = self.start_value(child) if restarts else number + 1
                child.number = number
        for child in children:
            self.validate(child)

    def vector(self, node: _Node) -> tuple[dict[int, int], bool]:
        """Level numbers on the path, and whether an ancestor is uncounted."""

        numbers: dict[int, int] = {}
        uncertain = False
        current: _Node | None = node
        while current is not None and current.parent is not None:
            numbers[current.depth + 1] = current.number
            if current is not node and (
                current.phantom or not self.counted(current)
            ):
                uncertain = True
            current = current.parent
        return numbers, uncertain


def _tree_numbers(
    paragraphs: list[_Paragraph], style: _ListStyle
) -> dict[int, tuple[dict[int, int], bool]]:
    tree = _Tree(style)
    nodes = [(paragraph, tree.add(paragraph)) for paragraph in paragraphs]
    tree.validate(tree.root)
    return {paragraph.order: tree.vector(node) for paragraph, node in nodes}


def _counter_numbers(
    paragraphs: list[_Paragraph], style: _ListStyle
) -> dict[int, dict[int, int]]:
    """The plain per-level counters of the producing office suite."""

    counters: dict[int, int] = {}
    result: dict[int, dict[int, int]] = {}
    for paragraph in paragraphs:
        level = paragraph.level + 1
        if paragraph.counted:
            level_style = style.levels.get(level)
            start = level_style.start if level_style is not None else 1
            if paragraph.restart_value is not None:
                value = paragraph.restart_value
            elif level in counters:
                value = counters[level] + 1
            else:
                value = start
            counters[level] = value
            for deeper in [key for key in counters if key > level]:
                del counters[deeper]
        result[paragraph.order] = dict(counters)
    return result


# ---------------------------------------------------------------------------
# Labels


def _label(
    paragraph: _Paragraph,
    vector: Mapping[int, int],
    uncertain_ancestor: bool,
    counters: Mapping[int, int] | None,
    styles: _Styles,
    *,
    mso: bool,
) -> ListLabel:
    style = paragraph.style
    level_number = paragraph.level + 1
    indent = EXPORT_INDENT * level_number
    if style is None:
        raise ListNumberingUnsupported("list_style_unresolved")
    level = style.levels.get(level_number)
    if level is None:
        raise ListNumberingUnsupported("list_level_undefined")
    if level.malformed:
        raise ListNumberingUnsupported(level.malformed)
    if level.kind != "number":
        raise ListNumberingUnsupported(f"{level.kind}_label")
    if level.is_legal:
        raise ListNumberingUnsupported("legal_numbering")
    evidence: dict[str, Any] = {
        "rule_version": LIST_LABEL_RULE_VERSION,
        "list_style": style.name,
        "list_style_origin": style.origin,
        "level": level_number,
        "num_format": level.num_format,
        "num_prefix": level.prefix,
        "num_suffix": level.suffix,
        "counted": paragraph.counted,
    }
    if not paragraph.counted:
        return ListLabel(
            status="unlabelled",
            export_prefix=indent + "  " + " ",
            evidence=evidence,
        )
    if level.num_format == "":
        if level.prefix or level.suffix or level.list_format:
            raise ListNumberingUnsupported("number_none_with_affixes")
        if mso:
            _check_word_format(level, styles, "")
        return ListLabel(
            status="unlabelled",
            export_prefix=indent + "  " + " ",
            evidence=evidence,
        )
    template = _effective_list_format(level)
    label, used = _expand_list_format(
        template, level_number, vector, style.levels, word_compatible=mso
    )
    if not label:
        raise ListNumberingUnsupported("label_empty")
    if level.position_mode != "label-alignment":
        # The printed gap is a fixed label width, not a character.
        raise ListNumberingUnsupported("label_width_and_position_mode")
    separator = _FOLLOWED_BY.get(level.followed_by)
    if separator is None:
        raise ListNumberingUnsupported("label_followed_by_unsupported")
    if any(target != level_number for target in used) and uncertain_ancestor:
        raise ListNumberingUnsupported("display_levels_phantom_ancestor")
    if mso:
        _check_word_format(level, styles, template)
        if counters is None:
            raise ListNumberingUnsupported("list_numbering_counters_missing")
        for target in used:
            if counters.get(target) != vector.get(target):
                raise ListNumberingUnsupported("list_numbering_models_disagree")
    evidence.update(
        {
            "number": vector.get(level_number),
            "list_format": template,
            "label_followed_by": level.followed_by,
            "start_value": level.start,
            "display_levels": level.display_levels,
            "restart": paragraph.restart,
        }
    )
    return ListLabel(
        status="labelled",
        label=label,
        separator=separator,
        export_prefix=indent + label + " ",
        evidence=evidence,
    )


def _check_word_format(level: _Level, styles: _Styles, template: str) -> None:
    """The Word list-format string must print the same template."""

    if level.word_format_name is None:
        return
    formats = styles.word_formats.get(level.word_format_name)
    if formats is None:
        raise ListNumberingUnsupported("word_list_format_malformed")
    if formats.get(level.level) != template:
        raise ListNumberingUnsupported("word_list_format_differs")


def document_generator(meta: ElementTree.Element | None) -> str:
    if meta is None:
        return ""
    node = meta.find(f".//{_TAG_GENERATOR}")
    return (node.text or "").strip() if node is not None else ""


def resolve_list_labels(
    content: ElementTree.Element,
    styles: ElementTree.Element | None = None,
    meta: ElementTree.Element | None = None,
) -> dict[int, ListLabel]:
    """Numbering of every paragraph that is in a list or may draw a number.

    The result maps ``id(element)`` of each affected ``text:p``/``text:h`` to
    its :class:`ListLabel`; paragraphs outside any list that draw nothing are
    absent.  ``content``/``styles``/``meta`` are the parsed ODF parts.
    """

    body = content.find(f".//{{{_OFFICE}}}text")
    if body is None:
        return {}
    resolved = _Styles(content, styles)
    mso = document_generator(meta).startswith(MSO_GENERATOR_PREFIX)
    walker = _Walker(resolved, mso=mso)
    walker.walk(body, None, False)
    result: dict[int, ListLabel] = dict(walker.outside)
    by_list: dict[str, list[_Paragraph]] = {}
    for paragraph in walker.paragraphs:
        by_list.setdefault(paragraph.list_id, []).append(paragraph)
    for paragraphs in by_list.values():
        tainted_from: int | None = None
        styles_used = {
            id(paragraph.style)
            for paragraph in paragraphs
            if paragraph.style is not None
        }
        if len(styles_used) > 1:
            tainted_from = -1
        for paragraph in paragraphs:
            if paragraph.taints_list and tainted_from is None:
                tainted_from = paragraph.order
        style = next(
            (paragraph.style for paragraph in paragraphs if paragraph.style),
            None,
        )
        real = [paragraph for paragraph in paragraphs if paragraph.source != "taint"]
        tree = _tree_numbers(real, style) if style is not None else {}
        counters = _counter_numbers(real, style) if style is not None else {}
        for paragraph in real:
            export_prefix = EXPORT_INDENT * (paragraph.level + 1)
            reason = paragraph.problem
            if reason is None and tainted_from is not None and (
                tainted_from < 0 or paragraph.order > tainted_from
            ):
                reason = "list_numbering_state_unsupported"
            if reason is None:
                vector, uncertain = tree[paragraph.order]
                try:
                    label = _label(
                        paragraph,
                        vector,
                        uncertain,
                        counters.get(paragraph.order),
                        resolved,
                        mso=mso,
                    )
                except ListNumberingUnsupported as exc:
                    reason = exc.reason
                else:
                    result[id(paragraph.element)] = label
                    continue
            result[id(paragraph.element)] = ListLabel(
                status="unsupported",
                export_prefix=export_prefix,
                reason=reason,
            )
    return result
